# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g gulp
  displayName: 'install gulp'

- script: |
    npm --no-git-tag-version version 0.0.$(Build.BuildId)
    echo //registry.npmjs.org/:_authToken=$(NPMAuthToken) > ~/.npmrc
    echo 'starting npm install'
    npm install
    echo 'starting gulp build'
    gulp build
  displayName: 'npm install and run gulp'

- script: |
    xcodebuild -project ./XCUITest/testApplication/testApplication.xcodeproj -scheme testApplication -destination 'platform=iOS Simulator,name=iphone 11' test
  displayName: 'run XCUITest to ensure that the framework for testing works'

- script: |
    xcrun simctl list
  displayName: 'list simulators'

- script: |
    npm install -g testcafe
    gulp build
    npm link
    npm test
  displayName: 'run tests'

- script: |
    npm run publish-please
  displayName: 'publish'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))